### ISSUE TITLE
tinyNET does not compile on MacOS 64b

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DoubangoTelecom/doubango#191]
```
What steps will reproduce the problem?
following technical documentation for recompilation of doubango, I reached that:
ld: duplicate symbol _type in .libs/libtinyNET_la-tnet_ice_ctx.o and 
.libs/libtinyNET_la-tnet_ice_candidate.o for architecture x86_64

What version of the product are you using? On what operating system?
branch 2.0
macosX 10.7.5
i686-apple-darwin11-llvm-gcc-4.2

Please provide any additional information below.
poking around to see where the error could come from, it appears that the 
culprit is tinyNET/src/ice/tnet_ice_utils.h:33
I suspect that, each .c file being compiled separately, the usual #ifndef / 
#def / #endif guards are not enough to protect from double inclusion. I have no 
idea how to fix that cleanly in the context of doubango.


```

Original issue reported on code.google.com by `agouaill...@gmail.com` on 11 Jan 2013 at 7:42
